import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the GitHub repository of this plugin
*/
`;

esbuild
  .build({
    banner: { js: banner },
    entryPoints: ["main.ts"],
    bundle: true,
    outfile: "main.js",
    format: "cjs",
    target: "es2020",
    platform: "node",
    external: ["obsidian", "electron"],
    logLevel: "info",
  })
  .catch(() => process.exit(1));
