/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the GitHub repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ExportIcsSchedulePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  defaultDurationMinutes: 60,
  alarmLeadMinutes: 0,
  allDayReminderHour: 9,
  defangDates: true,
  timezone: ""
};
var ICS_FOLDER = "\u9644\u4EF6/calendar-sync";
function stableUid(seed) {
  const fnv = (s, h0) => {
    let h = h0 >>> 0;
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i);
      h = Math.imul(h, 16777619) >>> 0;
    }
    return h >>> 0;
  };
  const a = fnv(seed, 2166136261);
  const b = fnv(seed, 16777619);
  return `${a.toString(16).padStart(8, "0")}${b.toString(16).padStart(8, "0")}@obsidian`;
}
function tzOffsetMs(date, tz) {
  const p = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    hour12: false,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit"
  }).formatToParts(date).reduce((a, x) => (a[x.type] = x.value, a), {});
  const hh = p.hour === "24" ? "00" : p.hour;
  const asUTC = Date.UTC(+p.year, +p.month - 1, +p.day, +hh, +p.minute, +p.second);
  return asUTC - date.getTime();
}
function wallToUtc(y, mo, d, h, mi, tz) {
  const naive = Date.UTC(y, mo - 1, d, h, mi, 0);
  let t = naive;
  for (let i = 0; i < 4; i++) {
    const nt = naive - tzOffsetMs(new Date(t), tz);
    if (nt === t) break;
    t = nt;
  }
  return new Date(t);
}
function fmtWallClock(d, tz) {
  const p = new Intl.DateTimeFormat("en-US", {
    timeZone: tz,
    hour12: false,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit"
  }).formatToParts(d).reduce((a, x) => (a[x.type] = x.value, a), {});
  const hh = p.hour === "24" ? "00" : p.hour;
  return `${p.year}${p.month}${p.day}T${hh}${p.minute}${p.second}`;
}
function offToIcal(ms) {
  const total = Math.round(ms / 6e4);
  const sign = total >= 0 ? "+" : "-";
  const a = Math.abs(total);
  return `${sign}${String(Math.floor(a / 60)).padStart(2, "0")}${String(a % 60).padStart(2, "0")}`;
}
var BYDAY = ["SU", "MO", "TU", "WE", "TH", "FR", "SA"];
function transitionRule(utcMs, fromOff) {
  const dt = new Date(utcMs + fromOff);
  const pad = (n) => String(n).padStart(2, "0");
  const y = dt.getUTCFullYear();
  const m = dt.getUTCMonth() + 1;
  const d = dt.getUTCDate();
  const wall = `${y}${pad(m)}${pad(d)}T${pad(dt.getUTCHours())}${pad(dt.getUTCMinutes())}00`;
  const daysInMonth = new Date(y, m, 0).getDate();
  const nth = Math.floor((d - 1) / 7) + 1;
  const ord = d + 7 > daysInMonth ? -1 : nth;
  const rule = `FREQ=YEARLY;BYMONTH=${m};BYDAY=${ord}${BYDAY[dt.getUTCDay()]}`;
  return { wall, rule };
}
function buildVtimezone(tz) {
  const year = (/* @__PURE__ */ new Date()).getUTCFullYear();
  const monthly = Array.from(
    { length: 12 },
    (_, m) => tzOffsetMs(new Date(Date.UTC(year, m, 15, 12, 0, 0)), tz)
  );
  const minOff = Math.min(...monthly);
  const maxOff = Math.max(...monthly);
  if (minOff === maxOff) {
    const o = offToIcal(minOff);
    return [
      "BEGIN:VTIMEZONE",
      `TZID:${tz}`,
      "BEGIN:STANDARD",
      "DTSTART:19700101T000000",
      `TZOFFSETFROM:${o}`,
      `TZOFFSETTO:${o}`,
      "TZNAME:LOCAL",
      "END:STANDARD",
      "END:VTIMEZONE"
    ];
  }
  const standardOff = minOff;
  const daylightOff = maxOff;
  const startUtc = Date.UTC(year, 0, 1);
  const endUtc = Date.UTC(year + 1, 0, 1);
  let sfUtc = null;
  let fbUtc = null;
  let prev = tzOffsetMs(new Date(startUtc), tz);
  for (let t = startUtc + 3600 * 1e3; t <= endUtc; t += 3600 * 1e3) {
    const cur = tzOffsetMs(new Date(t), tz);
    if (cur !== prev) {
      if (cur > prev) sfUtc = t;
      else fbUtc = t;
      prev = cur;
    }
  }
  const lines = ["BEGIN:VTIMEZONE", `TZID:${tz}`];
  if (fbUtc != null) {
    const s = transitionRule(fbUtc, daylightOff);
    lines.push(
      "BEGIN:STANDARD",
      `DTSTART:${s.wall}`,
      `TZOFFSETFROM:${offToIcal(daylightOff)}`,
      `TZOFFSETTO:${offToIcal(standardOff)}`,
      "TZNAME:\u6807\u51C6\u65F6",
      `RRULE:${s.rule}`,
      "END:STANDARD"
    );
  }
  if (sfUtc != null) {
    const d = transitionRule(sfUtc, standardOff);
    lines.push(
      "BEGIN:DAYLIGHT",
      `DTSTART:${d.wall}`,
      `TZOFFSETFROM:${offToIcal(standardOff)}`,
      `TZOFFSETTO:${offToIcal(daylightOff)}`,
      "TZNAME:\u590F\u4EE4\u65F6",
      `RRULE:${d.rule}`,
      "END:DAYLIGHT"
    );
  }
  lines.push("END:VTIMEZONE");
  return lines;
}
var ExportIcsSchedulePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.addSettingTab(new ExportIcsScheduleSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        menu.addItem(
          (item) => item.setTitle("\u21E2 \u5BFC\u51FA\u5230 ICS\u65E5\u7A0B").setIcon("calendar-plus").onClick(() => this.launchFromEditor(editor))
        );
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem(
            (item) => item.setTitle("\u21E2 \u672C\u9875\u6240\u6709\u4EFB\u52A1 \u2192 ICS\u65E5\u7A0B").setIcon("calendar-plus").onClick(() => this.launchFile(file))
          );
        }
      })
    );
    this.addRibbonIcon("calendar-plus", "\u672C\u9875\u4EFB\u52A1 \u2192 ICS\u65E5\u7A0B", () => {
      const f = this.app.workspace.getActiveFile();
      if (f) this.launchFile(f);
      else new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u542B\u4EFB\u52A1\u7684\u7B14\u8BB0");
    });
    this.addCommand({
      id: "send-current-task",
      name: "\u5F53\u524D\u4EFB\u52A1 \u2192 ICS\u65E5\u7A0B",
      editorCallback: (editor) => this.launchFromEditor(editor)
    });
    this.addCommand({
      id: "send-all-tasks-in-file",
      name: "\u5F53\u524D\u6587\u4EF6\u6240\u6709\u4EFB\u52A1 \u2192 ICS\u65E5\u7A0B",
      callback: () => {
        const f = this.app.workspace.getActiveFile();
        if (f) this.launchFile(f);
        else new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u542B\u4EFB\u52A1\u7684\u7B14\u8BB0");
      }
    });
  }
  /** 从编辑器智能定位目标任务（光标行 → 向上3行 → 选中文本）*/
  launchFromEditor(editor) {
    let task = this.findTaskAtCursor(editor);
    if (!task) {
      const sel = editor.getSelection();
      if (sel) {
        const m = sel.match(/^\s*-\s*\[\s\]\s*(.+)$/m);
        if (m) task = this.parseTask(m[1].trim());
      }
    }
    if (task) {
      return this.launch([task], this.app.workspace.getActiveFile() ?? void 0);
    }
    new import_obsidian.Notice(
      "\u672A\u5728\u6B64\u5904\u627E\u5230\u5E26\u65F6\u95F4\u7684 - [ ] \u4EFB\u52A1\n\u8BF7\u628A\u5149\u6807\u653E\u5728\u4EFB\u52A1\u884C\uFF0C\u6216\u7528\u547D\u4EE4\u9762\u677F\u9009\u300C\u5F53\u524D\u6587\u4EF6\u6240\u6709\u4EFB\u52A1 \u2192 ICS\u65E5\u7A0B\u300D"
    );
  }
  /** 光标所在任务行（向上找 3 行）*/
  findTaskAtCursor(editor) {
    const cursor = editor.getCursor();
    for (let i = cursor.line; i >= Math.max(0, cursor.line - 3); i--) {
      const m = editor.getLine(i).match(/^\s*-\s*\[\s\]\s*(.+)$/);
      if (m) return this.parseTask(m[1].trim());
    }
    return null;
  }
  /**
   * 解析任务（due date 与提醒时间可以共存）：
   * - 只有 due date（`📅 2026-09-05` / `(@2026-09-05)`）→ 全天日程
   * - due date + 具体提醒时刻（`⏰ 15:00` 或 `(@2026-09-05 15:00)`）→ 定时日程，以提醒时刻为准
   */
  parseTask(raw) {
    let beginTime;
    let allDayDate;
    let dueDate;
    let remindDate;
    let remindTime;
    let emojiTime;
    let dvDate;
    const rm = raw.match(/\(@(\d{4}-\d{2}-\d{2})(?:\s+(\d{2}:\d{2}))?\)/);
    if (rm) {
      remindDate = rm[1];
      if (rm[2]) remindTime = rm[2];
    }
    const dm = raw.match(/📅\s*(\d{4}-\d{2}-\d{2})/);
    if (dm) dueDate = dm[1];
    const tm = raw.match(/⏰\s*(\d{2}:\d{2})/);
    if (tm) emojiTime = tm[1];
    const dvm = raw.match(/\[date::\s*(\d{4}-\d{2}-\d{2})\]/);
    if (dvm) dvDate = dvm[1];
    const time = remindTime || emojiTime;
    if (time) {
      const date = remindTime ? remindDate || dueDate || dvDate : dueDate || remindDate || dvDate;
      if (date) beginTime = wallToUtc(+date.slice(0, 4), +date.slice(5, 7), +date.slice(8, 10), +time.slice(0, 2), +time.slice(3, 5), this.resolveTz());
    }
    if (!beginTime) {
      const allDay = dueDate || remindDate || dvDate;
      if (allDay) allDayDate = allDay.replace(/-/g, "");
    }
    const title = raw.replace(/\(@[^)]+\)/g, "").replace(/📅\s*\d{4}-\d{2}-\d{2}/gu, "").replace(/⏰\s*\d{2}:\d{2}/gu, "").replace(/🛁\s*\d{4}-\d{2}-\d{2}/gu, "").replace(/🔁\s*[^\s]+/gu, "").replace(/\[date::[^\]]+\]/g, "").replace(/[\u{1F300}-\u{1F9FF}\u{2600}-\u{27BF}]/gu, "").replace(/\s+/g, " ").trim();
    return { raw, title, beginTime, allDayDate };
  }
  /** 构造 ICS（定时事件按生效时区用 TZID，全天事件用 VALUE=DATE，每个事件带 VALARM 提醒）*/
  buildIcs(tasks, file) {
    const pad = (n) => String(n).padStart(2, "0");
    const fmtUTC = (d) => `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`;
    const tz = this.resolveTz();
    const TZID = tz;
    const fmtLocal = (d) => fmtWallClock(d, tz);
    const esc = (s) => s.replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,").replace(/\r?\n/g, "\\n");
    const nextDay = (c) => {
      const y = +c.slice(0, 4), m = +c.slice(4, 6), d = +c.slice(6, 8);
      const dt = new Date(Date.UTC(y, m - 1, d + 1));
      return `${dt.getUTCFullYear()}${pad(dt.getUTCMonth() + 1)}${pad(dt.getUTCDate())}`;
    };
    const allDayTrigger = (c) => {
      const h = Math.min(23, Math.max(0, this.settings.allDayReminderHour));
      const dt = wallToUtc(+c.slice(0, 4), +c.slice(4, 6), +c.slice(6, 8), h, 0, tz);
      return fmtUTC(dt);
    };
    const lines = [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:-//obsidian//export-ics-schedule//CN",
      "CALSCALE:GREGORIAN"
    ];
    lines.push(...buildVtimezone(tz));
    const stamp = fmtUTC(/* @__PURE__ */ new Date());
    const lead = Math.max(0, this.settings.alarmLeadMinutes);
    for (const t of tasks) {
      const uid = stableUid(`${file?.path || "obsidian"}::${t.title || "task"}`);
      const summary = esc(t.title || "Obsidian \u4EFB\u52A1");
      lines.push("BEGIN:VEVENT");
      lines.push(`UID:${uid}`);
      lines.push(`DTSTAMP:${stamp}`);
      if (t.allDayDate) {
        lines.push(`DTSTART;VALUE=DATE:${t.allDayDate}`);
        lines.push(`DTEND;VALUE=DATE:${nextDay(t.allDayDate)}`);
      } else {
        const begin = t.beginTime;
        const end = new Date(begin.getTime() + this.settings.defaultDurationMinutes * 60 * 1e3);
        lines.push(`DTSTART;TZID=${TZID}:${fmtLocal(begin)}`);
        lines.push(`DTEND;TZID=${TZID}:${fmtLocal(end)}`);
      }
      lines.push(`SUMMARY:${summary}`);
      lines.push(`DESCRIPTION:\u6765\u6E90\uFF1A${esc(this.sourceLabel(file))}`);
      lines.push("BEGIN:VALARM");
      lines.push("ACTION:DISPLAY");
      if (t.allDayDate) {
        lines.push(`TRIGGER;VALUE=DATE-TIME:${allDayTrigger(t.allDayDate)}`);
      } else {
        lines.push(`TRIGGER;RELATED=START:-PT${lead}M`);
      }
      lines.push(`DESCRIPTION:${summary}`);
      lines.push("END:VALARM");
      lines.push("END:VEVENT");
    }
    lines.push("END:VCALENDAR");
    return lines.join("\r\n");
  }
  /** 描述文本：Obsidian/路径/笔记名（去掉 .md 后缀），如 Obsidian/20待办/xxx项目/xxx行动 */
  sourceLabel(file) {
    if (!file) return "Obsidian";
    const label = `Obsidian/${file.path.replace(/\.md$/i, "")}`;
    return this.settings.defangDates ? this.defangDates(label) : label;
  }
  /**
   * 日期脱敏：在日期的数字之间插入零宽空格（U+200B）。
   * 显示效果完全不变，但字符串不再匹配 YYYY-MM-DD / YYYYMMDD，
   * 日历的「智能识别日程」就抓不到日期、不会再据此多建一个事件。
   */
  defangDates(s) {
    return s.replace(/(\d{4})([-/.])(\d{2})\2(\d{2})/g, "$1$2\u200B$3$2\u200B$4").replace(/\b(\d{4})(\d{2})(\d{2})\b/g, "$1\u200B$2\u200B$3");
  }
  /** 解析生效时区：设置项优先；留空则用手机当前时区；兜底 Asia/Shanghai */
  resolveTz() {
    const raw = (this.settings.timezone || "").trim();
    if (raw) {
      try {
        new Intl.DateTimeFormat("en-US", { timeZone: raw });
        return raw;
      } catch {
      }
    }
    try {
      const z = Intl.DateTimeFormat().resolvedOptions().timeZone;
      if (z) return z;
    } catch {
    }
    return "Asia/Shanghai";
  }
  /** 把标题转成合法文件名 */
  safeName(title) {
    const cleaned = (title || "task").replace(/[\\/:*?"<>|]/g, "_").replace(/\s+/g, "_").slice(0, 40).replace(/_+$/, "");
    return cleaned || `task-${Date.now()}`;
  }
  /**
   * 写入 ICS 并打开：
   * - 手机端：用 openWithDefaultApp 原生桥把 .ics 交给系统日历（系统日历）接管导入。
   * - 桌面端：无此桥，写出文件后用系统默认程序打开（.ics 若已关联 Outlook 等则直接导入），
   *   并提示文件路径，供手动导入到 Outlook / Google Calendar。
   */
  async writeAndOpenIcs(tasks, file) {
    const ics = this.buildIcs(tasks, file);
    const folder = ICS_FOLDER;
    const adapter = this.app.vault.adapter;
    if (!await adapter.exists(folder)) {
      await adapter.mkdir(folder);
    }
    const relPath = tasks.length === 1 ? `${folder}/${this.safeName(tasks[0].title)}.ics` : `${folder}/${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}_\u6279\u91CF\u4EFB\u52A1.ics`;
    await adapter.write(relPath, ics);
    if (import_obsidian.Platform.isMobile) {
      const appAny = this.app;
      if (typeof appAny.openWithDefaultApp === "function") {
        appAny.openWithDefaultApp(relPath);
        new import_obsidian.Notice(
          tasks.length === 1 ? '\u{1F4C5} \u5DF2\u751F\u6210\u65E5\u5386\u6587\u4EF6\u5E76\u7528\u7CFB\u7EDF\u6253\u5F00\uFF0C\u8BF7\u5728\u7CFB\u7EDF\u65E5\u5386\u70B9"\u4FDD\u5B58"' : `\u{1F4C5} \u5DF2\u751F\u6210 ${tasks.length} \u6761\u4E8B\u4EF6\u7684\u65E5\u5386\u6587\u4EF6\uFF0C\u7CFB\u7EDF\u65E5\u5386\u5BFC\u5165\u540E\u9010\u6761\u4FDD\u5B58`
        );
      } else {
        new import_obsidian.Notice("\u5F53\u524D Obsidian \u7248\u672C\u65E0 openWithDefaultApp\uFF0C\u8BF7\u624B\u52A8\u6253\u5F00: " + relPath);
      }
      return;
    }
    const full = typeof adapter.getFullPath === "function" ? adapter.getFullPath(relPath) : relPath;
    let opened = false;
    try {
      if (typeof adapter.open === "function") {
        await adapter.open(full);
        opened = true;
      }
    } catch {
    }
    if (opened) {
      new import_obsidian.Notice(
        tasks.length === 1 ? "\u{1F4C5} \u5DF2\u751F\u6210\u65E5\u5386\u6587\u4EF6\u5E76\u5C1D\u8BD5\u7528\u9ED8\u8BA4\u7A0B\u5E8F\u6253\u5F00\uFF08\u82E5 .ics \u5DF2\u5173\u8054 Outlook \u7B49\u4F1A\u76F4\u63A5\u5BFC\u5165\uFF09" : `\u{1F4C5} \u5DF2\u751F\u6210 ${tasks.length} \u6761\u4E8B\u4EF6\u7684\u65E5\u5386\u6587\u4EF6\u5E76\u5C1D\u8BD5\u6253\u5F00`,
        8e3
      );
    } else {
      new import_obsidian.Notice("\u5DF2\u751F\u6210\u65E5\u5386\u6587\u4EF6\uFF1A\n" + full + "\n\u8BF7\u5728 Outlook / Google Calendar \u4E2D\u5BFC\u5165", 8e3);
    }
  }
  /** 跳转：单条或批量 */
  launch(tasks, file) {
    const valid = tasks.filter((t) => t.beginTime || t.allDayDate);
    if (!valid.length) {
      return new import_obsidian.Notice(
        "\u2753 \u4EFB\u52A1\u672A\u6307\u5B9A\u65F6\u95F4\uFF0C\u65E0\u6CD5\u521B\u5EFA\u65E5\u5386\u4E8B\u4EF6\n\u5B9A\u65F6\uFF1A(@2026-09-05 09:00) \u6216 \u{1F4C5} 2026-09-05 \u23F0 09:00\n\u5168\u5929\uFF1A(@2026-09-05) \u6216 \u{1F4C5} 2026-09-05"
      );
    }
    this.writeAndOpenIcs(valid, file);
  }
  /** 批量跳转文件所有任务 */
  async launchFile(f) {
    const content = await this.app.vault.read(f);
    const tasks = content.split("\n").map((l) => l.match(/^\s*-\s*\[\s\]\s*(.+)$/)).filter((m) => !!m).map((m) => this.parseTask(m[1].trim()));
    const valid = tasks.filter((t) => t.beginTime || t.allDayDate);
    if (!valid.length) {
      return new import_obsidian.Notice(
        "\u672C\u9875\u6CA1\u6709\u5E26\u65F6\u95F4\u7684 - [ ] \u4EFB\u52A1\n\u5B9A\u65F6\uFF1A(@2026-09-05 09:00) \u6216 \u{1F4C5} 2026-09-05 \u23F0 09:00\n\u5168\u5929\uFF1A(@2026-09-05) \u6216 \u{1F4C5} 2026-09-05"
      );
    }
    this.writeAndOpenIcs(valid, f);
  }
};
var ExportIcsScheduleSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", { text: "\u5BFC\u51FAICS\uFF08Export ICS\uFF09" });
    containerEl.createEl("p", {
      text: "\u6253\u5F00\u542B\u4EFB\u52A1\u7684\u7B14\u8BB0\uFF0C\u70B9\u51FB\u529F\u80FD\u533A\u7684\u300E\u672C\u9875\u4EFB\u52A1 \u2192 ICS\u65E5\u7A0B\u300F\u56FE\u6807\uFF0C\u5373\u53EF\u628A\u672C\u9875\u6240\u6709\u5E26\u65F6\u95F4\u7684 - [ ] \u4EFB\u52A1\u751F\u6210 .ics \u5E76\u5BFC\u5165\u7CFB\u7EDF\u65E5\u5386\uFF08\u547D\u4EE4\u9762\u677F\u4E5F\u53EF\u641C\u300CICS\u65E5\u7A0B\u300D\uFF09\u3002\u5199\u4E86\u5177\u4F53\u65F6\u523B \u2192 \u5B9A\u65F6\u65E5\u7A0B\uFF1B\u53EA\u5199\u65E5\u671F \u2192 \u5168\u5929\u65E5\u7A0B\u3002\u4E24\u8005\u90FD\u4F1A\u5E26\u63D0\u9192\u3002"
    });
    containerEl.createEl("p", {
      text: "\u4E8B\u4EF6\u53BB\u91CD\u89C4\u5219\uFF1A\u540C\u4E00\u4EFB\u52A1\u7684\u300C\u7B14\u8BB0\u8DEF\u5F84 + \u4EFB\u52A1\u6807\u9898\u300D\u90FD\u4E0D\u53D8\uFF0C\u91CD\u5BFC\u65F6\u6309\u76F8\u540C UID \u66F4\u65B0\u539F\u4E8B\u4EF6\u3001\u4E0D\u518D\u91CD\u590D\uFF1B\u82E5\u6539\u4E86\u4EFB\u52A1\u6807\u9898\uFF0C\u6216\u79FB\u52A8/\u91CD\u547D\u540D\u4E86\u7B14\u8BB0\u5BFC\u81F4\u8DEF\u5F84\u53D8\u5316\uFF0C\u90FD\u4F1A\u751F\u6210\u5168\u65B0 UID\uFF0C\u7CFB\u7EDF\u65E5\u5386\u5F53\u4F5C\u65B0\u4E8B\u4EF6\u65B0\u5EFA\u4E00\u4EFD\uFF0C\u65E7\u7684\uFF08\u65E7\u6807\u9898\u6216\u65E7\u8DEF\u5F84\uFF09\u4E8B\u4EF6\u4E0D\u4F1A\u81EA\u52A8\u6D88\u5931\uFF0C\u9700\u5728\u65E5\u5386\u91CC\u624B\u52A8\u5220\u9664\u3002"
    });
    const TZ_CITIES = {
      [-11]: "\u5E15\u679C\u5E15\u679C\uFF08\u7F8E\u5C5E\u8428\u6469\u4E9A\uFF09\u3001\u4E2D\u9014\u5C9B",
      [-10]: "\u6A80\u9999\u5C71\uFF08\u590F\u5A01\u5937\uFF09",
      [-9]: "\u5B89\u514B\u96F7\u5947\uFF08\u963F\u62C9\u65AF\u52A0\uFF09",
      [-8]: "\u6D1B\u6749\u77F6\u3001\u6E29\u54E5\u534E",
      [-7]: "\u4E39\u4F5B\u3001\u83F2\u5C3C\u514B\u65AF\u3001\u57C3\u5FB7\u8499\u987F",
      [-6]: "\u829D\u52A0\u54E5\u3001\u58A8\u897F\u54E5\u57CE\u3001\u5371\u5730\u9A6C\u62C9\u57CE",
      [-5]: "\u7EBD\u7EA6\u3001\u6CE2\u54E5\u5927",
      [-4]: "\u54C8\u5229\u6CD5\u514B\u65AF\u3001\u62C9\u5DF4\u65AF\u3001\u9A6C\u7459\u65AF",
      [-3]: "\u5723\u4FDD\u7F57\u3001\u5E03\u5B9C\u8BFA\u65AF\u827E\u5229\u65AF\u3001\u8499\u7279\u7EF4\u7684\u4E9A",
      [-2]: "\u5357\u4E54\u6CBB\u4E9A\u3001\u8D39\u5C14\u5357\u591A\xB7\u8FEA\u8BFA\u7F57\u5C3C\u4E9A",
      [-1]: "\u4E9A\u901F\u5C14\uFF08\u8461\u8404\u7259\uFF09\u3001\u4F5B\u5F97\u89D2",
      [0]: "\u4F26\u6566\u3001\u91CC\u65AF\u672C\u3001\u963F\u514B\u62C9",
      [1]: "\u5DF4\u9ECE\u3001\u67CF\u6797\u3001\u7F57\u9A6C\u3001\u9A6C\u5FB7\u91CC",
      [2]: "\u5F00\u7F57\u3001\u8D6B\u5C14\u8F9B\u57FA\u3001\u4F0A\u65AF\u5766\u5E03\u5C14",
      [3]: "\u83AB\u65AF\u79D1\u3001\u5185\u7F57\u6BD4\u3001\u5DF4\u683C\u8FBE",
      [4]: "\u8FEA\u62DC\u3001\u5DF4\u5E93",
      [5]: "\u5361\u62C9\u5947\u3001\u4F0A\u65AF\u5170\u5821",
      [6]: "\u8FBE\u5361\u3001\u963F\u65AF\u5854\u7EB3",
      [7]: "\u66FC\u8C37\u3001\u96C5\u52A0\u8FBE\u3001\u6CB3\u5185",
      [8]: "\u5317\u4EAC\u3001\u4E0A\u6D77\u3001\u9999\u6E2F\u3001\u65B0\u52A0\u5761\u3001\u73C0\u65AF",
      [9]: "\u4E1C\u4EAC\u3001\u9996\u5C14",
      [10]: "\u6089\u5C3C\u3001\u58A8\u5C14\u672C",
      [11]: "\u970D\u5C3C\u4E9A\u62C9",
      [12]: "\u60E0\u7075\u987F\u3001\u82CF\u74E6"
    };
    const TZ_OPTIONS = [["", "\u81EA\u52A8\uFF08\u7CFB\u7EDF\u5F53\u524D\u65F6\u533A\uFF09"]];
    for (let off = -11; off <= 12; off++) {
      const etc = off === 0 ? "UTC" : `Etc/GMT${off > 0 ? "-" : "+"}${Math.abs(off)}`;
      const sign = off > 0 ? "+" : off < 0 ? "-" : "";
      const cities = TZ_CITIES[off] || "";
      TZ_OPTIONS.push([etc, `UTC${sign}${Math.abs(off)}\uFF1A${cities}`]);
    }
    new import_obsidian.Setting(containerEl).setName("\u65F6\u533A").setDesc("\u9009\u300C\u81EA\u52A8\u300D\u5373\u7528\u7CFB\u7EDF\u5F53\u524D\u65F6\u533A\uFF08\u5168\u4EE5\u5F53\u5730\u65F6\u95F4\uFF09\u3002\u5982\u9700\u56FA\u5B9A\u65F6\u533A\uFF0C\u4ECE 24 \u4E2A\u6574\u70B9\u65F6\u533A\uFF08UTC-11 ~ UTC+12\uFF09\u4E2D\u9009\u3002").addDropdown((dd) => {
      const cur = this.plugin.settings.timezone || "";
      for (const [val, label] of TZ_OPTIONS) dd.addOption(val, label);
      if (cur && !TZ_OPTIONS.some(([v]) => v === cur)) {
        try {
          new Intl.DateTimeFormat("en-US", { timeZone: cur });
          dd.addOption(cur, `${cur}\uFF08\u81EA\u5B9A\u4E49\uFF09`);
        } catch {
        }
      }
      dd.setValue(cur).onChange(async (value) => {
        this.plugin.settings.timezone = value;
        await this.plugin.saveData(this.plugin.settings);
      });
    });
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u4E8B\u4EF6\u65F6\u957F\uFF08\u5206\u949F\uFF09").setDesc("\u5B9A\u65F6\u4EFB\u52A1\u672A\u6307\u5B9A\u7ED3\u675F\u65F6\u95F4\u65F6\uFF0C\u81EA\u52A8\u586B\u591A\u5C11\u5206\u949F\uFF08\u9ED8\u8BA4 60\uFF09").addText(
      (text) => text.setValue(String(this.plugin.settings.defaultDurationMinutes)).onChange(async (value) => {
        this.plugin.settings.defaultDurationMinutes = parseInt(value, 10) || 60;
        await this.plugin.saveData(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5B9A\u65F6\u65E5\u7A0B\u63D0\u9192\u63D0\u524D\uFF08\u5206\u949F\uFF09").setDesc("0 = \u51C6\u65F6\u63D0\u9192\uFF08\u4E8B\u4EF6\u5F00\u59CB\u65F6\u54CD\uFF09\u3002\u82E5\u65E5\u5386\u5FFD\u7565 0 \u5206\u949F\uFF0C\u53EF\u6539\u6210 5 \u6216 10").addText(
      (text) => text.setValue(String(this.plugin.settings.alarmLeadMinutes)).onChange(async (value) => {
        this.plugin.settings.alarmLeadMinutes = parseInt(value, 10) || 0;
        await this.plugin.saveData(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5168\u5929\u65E5\u7A0B\u63D0\u9192\u65F6\u523B\uFF08\u70B9\uFF09").setDesc("\u5168\u5929\u4E8B\u4EF6\u6CA1\u6709\u65F6\u95F4\u70B9\uFF0C\u7EDF\u4E00\u5728\u5F53\u5929\u8FD9\u4E2A\u65F6\u523B\u63D0\u9192\uFF080-23\uFF0C\u9ED8\u8BA4 9 \u70B9\uFF09").addText(
      (text) => text.setValue(String(this.plugin.settings.allDayReminderHour)).onChange(async (value) => {
        const h = parseInt(value, 10);
        this.plugin.settings.allDayReminderHour = Number.isNaN(h) ? 9 : Math.min(23, Math.max(0, h));
        await this.plugin.saveData(this.plugin.settings);
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u63CF\u8FF0\u91CC\u7684\u65E5\u671F\u8131\u654F").setDesc(
      "\u7B14\u8BB0\u540D\u542B\u65E5\u671F\u65F6\uFF08\u5982\u65E5\u8BB0 2026-09-04\uFF09\uFF0C\u63D2\u5165\u4E0D\u53EF\u89C1\u5B57\u7B26\u6253\u65AD\u65E5\u671F\uFF0C\u907F\u514D\u65E5\u5386\u300C\u667A\u80FD\u8BC6\u522B\u65E5\u7A0B\u300D\u636E\u6B64\u518D\u5EFA\u4E00\u4E2A\u91CD\u590D\u4E8B\u4EF6\u3002\u663E\u793A\u6548\u679C\u4E0D\u53D8\u3002"
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.defangDates).onChange(async (value) => {
        this.plugin.settings.defangDates = value;
        await this.plugin.saveData(this.plugin.settings);
      })
    );
  }
};
